apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  hackers-org-p4:
    if: ${{ fromJSON(inputs.manifest)['hackers-org-p4']['index.docker.io/cloudbeesdemo/hackers-organized'].deploy }}
    uses: cloudbees-days/hackers-org-p4/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['hackers-org-p4']['index.docker.io/cloudbeesdemo/hackers-organized'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['hackers-org-p4']['index.docker.io/cloudbeesdemo/hackers-organized'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
